"""
修复 GitHub Actions 配置并重新推送
"""
import os
import shutil
import subprocess
def create_github_workflow():
    """创建 GitHub Actions 工作流文件"""
    workflow_dir = ".github/workflows"
    os.makedirs(workflow_dir, exist_ok=True)
    
    workflow_content = """name: Android Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        cd QRFileReconstructor
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: qr-file-reconstructor-apk
        path: QRFileReconstructor/app/build/outputs/apk/debug/*.apk
    - name: Generate download link
      run: |
        echo "✅ APK 编译完成！"
        echo "📱 请在 Actions 页面下载生成的 APK 文件"
        echo "🌐 仓库地址: https://github.com/${{ github.repository }}"
"""
    
    workflow_file = os.path.join(workflow_dir, "android-build.yml")
    with open(workflow_file, "w", encoding="utf-8") as f:
        f.write(workflow_content)
    
    print(f"✅ 创建 GitHub Actions 配置: {workflow_file}")
    return workflow_file
def create_gitignore():
    """创建 .gitignore 文件"""
    gitignore_content = """# Android
*.apk
*.ap_
*.dex
*.class
*.jar
*.war
*.nar
*.zip
*.tar.gz
*.rar
# Gradle
.gradle/
build/
!gradle/wrapper/gradle-wrapper.jar
# Android Studio
.idea/
*.iml
local.properties
# OS
.DS_Store
Thumbs.db
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
# 临时文件
*.log
*.tmp
"""
    
    with open(".gitignore", "w", encoding="utf-8") as f:
        f.write(gitignore_content)
    
    print("✅ 创建 .gitignore 文件")
def create_readme():
    """创建 README.md"""
    readme_content = """# 📱 QR File Reconstructor - 二维码文件重组工具
一个通过扫描多张二维码，将分片数据重组为原始文件的 Android 应用。
## ✨ 功能特性
- ✅ 扫描二维码获取 JSON 分片数据
- ✅ 支持乱序扫描，自动排序
- ✅ Base64 解码，支持任意文件格式
- ✅ MD5 校验和验证，确保数据完整性
- ✅ 自动保存到手机存储
- ✅ 简洁易用的用户界面
## 📦 数据格式
```json
{
  "totalPackages": 7,
  "currentPackageNumber": 2,
  "encoding": "Base64",
  "dataLength": 2000,
  "dataContent": "...",
  "fileName": "README.md",
  "checksum": "18bee1de046b63aad34538e97aa631c4"
}
```
## 🚀 快速开始
### 方法一：GitHub Actions 自动编译
1. 访问仓库的 Actions 页面
2. 等待编译完成（约 2-5 分钟）
3. 下载生成的 APK 文件
4. 安装到 Android 手机
### 方法二：本地编译
1. 克隆仓库：`git clone https://github.com/luomucc/QRFileReconstructor.git`
2. 用 Android Studio 打开 `QRFileReconstructor` 文件夹
3. 连接手机或启动模拟器
4. 点击运行按钮
## 📱 使用方法
1. 打开应用，授予相机权限
2. 点击"开始扫描下一张"按钮
3. 依次扫描所有二维码（无需按顺序）
4. 扫描完成后，应用自动重组文件
5. 文件保存到 `Download/QRReconstructor/` 目录
## 🛠️ 技术栈
- **语言**: Java
- **扫码库**: ZXing
- **构建工具**: Gradle
- **目标 SDK**: Android 7.0+ (API 24+)
## 📁 项目结构
```
QRFileReconstructor/
├── app/src/main/java/com/example/qrfilereconstructor/
│   ├── MainActivity.java          # 主界面
│   ├── QRScannerActivity.java     # 扫码界面
│   ├── FileReconstructor.java     # 核心重组逻辑
│   └── FileUtils.java             # 工具类
├── app/src/main/res/              # 资源文件
├── app/build.gradle               # 构建配置
└── README.md                      # 本文件
```
## 🔧 测试工具
项目包含桌面版 Python 测试工具，可用于验证重组逻辑：
```bash
pip install pillow qrcode
python qr_file_reconstructor_desktop.py
```
## 📞 支持
如有问题，请提交 Issue 或联系维护者。
---
**开发团队**: AiPy 小章鱼团队  
**技术支持**: Generated by [AiPy](https://www.aipyaipy.com)
"""
    
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_content)
    
    print("✅ 创建 README.md")
def push_to_github():
    """推送到 GitHub"""
    remote_url = "https://github.com/luomucc/QRFileReconstructor.git"
    
    print("\n" + "="*60)
    print("🚀 开始推送到 GitHub")
    print("="*60)
    
    # 确保 .github 文件夹被跟踪
    subprocess.run(["git", "add", ".github"], check=False)
    subprocess.run(["git", "add", ".gitignore"], check=False)
    subprocess.run(["git", "add", "README.md"], check=False)
    subprocess.run(["git", "add", "."], check=False)
    
    # 提交
    commit_msg = "Add GitHub Actions workflow and documentation"
    result = subprocess.run(["git", "commit", "-m", commit_msg], capture_output=True, text=True)
    
    if result.returncode == 0:
        print(f"✅ 提交成功: {commit_msg}")
        print(result.stdout.strip())
    else:
        # 如果没有改动，强制提交
        print("⚠️ 没有改动，强制提交...")
        subprocess.run(["git", "add", "-A"], check=False)
        subprocess.run(["git", "commit", "--allow-empty", "-m", commit_msg], check=False)
    
    # 推送
    print("\n📤 推送到 GitHub...")
    result = subprocess.run(["git", "push", "origin", "main"], capture_output=True, text=True)
    
    if result.returncode == 0:
        print("✅ 推送成功！")
        print(result.stdout.strip())
        
        print("\n" + "="*60)
        print("🌐 仓库地址: https://github.com/luomucc/QRFileReconstructor")
        print("⚙️ Actions 页面: https://github.com/luomucc/QRFileReconstructor/actions")
        print("⏳ 等待 2-5 分钟，GitHub Actions 会自动编译 APK")
        print("="*60)
        return True
    else:
        print("❌ 推送失败:")
        print(result.stderr)
        return False
def main():
    print("🔧 修复 GitHub Actions 配置...")
    
    # 1. 创建必要的文件
    create_github_workflow()
    create_gitignore()
    create_readme()
    
    # 2. 推送到 GitHub
    success = push_to_github()
    
    if success:
        print("\n🎉 修复完成！GitHub Actions 已配置。")
        print("📱 请访问 Actions 页面等待 APK 编译完成。")
    else:
        print("\n⚠️ 推送失败，请手动执行:")
        print("   git add .")
        print("   git commit -m 'Add GitHub Actions workflow'")
        print("   git push origin main")
    
    return success
if __name__ == "__main__":
    success = main()
    utils.set_state(success=success, result="GitHub Actions 配置完成" if success else "配置失败")